import { create } from "zustand";
import type { VocabularyState, Vocabulary } from "@/types/vocabulary";

const defaultVocabulary: Vocabulary = {
    name: "Dictionary",
    progress: 50,
    words: [
        { word: "Perseverance", translation: "Beharrlichkeit" },
        { word: "Curiosity", translation: "Neugier" },
        { word: "Ambition", translation: "Ehrgeiz" },
        { word: "Diligence", translation: "Fleiß" },
        { word: "Integrity", translation: "Integrität" },
        { word: "Respect", translation: "Respekt" },
        { word: "Kindness", translation: "Freundlichkeit" },
        { word: "Ticket", translation: "Fahrkarte" },
        { word: "Luggage", translation: "Gepäck" },
        { word: "Airport", translation: "Flughafen" },
        { word: "Train", translation: "Zug" },
        { word: "Negotiation", translation: "Verhandlung" },
        { word: "Invoice", translation: "Rechnung" },
        { word: "Profit", translation: "Gewinn" },
        { word: "Strategy", translation: "Strategie" },
        { word: "Contract", translation: "Vertrag" },
        { word: "Client", translation: "Kunde" },
        { word: "Presentation", translation: "Präsentation" },
        { word: "Budget", translation: "Haushalt" },
        { word: "Deadline", translation: "Frist" },
        { word: "Hello", translation: "Hallo" },
        { word: "Thank you", translation: "Danke" },
        { word: "Sorry", translation: "Entschuldigung" },
        { word: "Bread", translation: "Brot" },
        { word: "Water", translation: "Wasser" },
        { word: "Apple", translation: "Apfel" },
        { word: "Cheese", translation: "Käse" },
        { word: "Coffee", translation: "Kaffee" },
        { word: "Juice", translation: "Saft" },
        { word: "Salt", translation: "Salz" },
        { word: "Butter", translation: "Butter" },
        { word: "Egg", translation: "Ei" },
        { word: "Fish", translation: "Fisch" },
    ],
};

const defaultVocabularies: Vocabulary[] = [
    {
        name: "My Main Dictionary",
        progress: 50,
        words: [
            { word: "Perseverance", translation: "Beharrlichkeit" },
            { word: "Curiosity", translation: "Neugier" },
            { word: "Ambition", translation: "Ehrgeiz" },
            { word: "Diligence", translation: "Fleiß" },
            { word: "Integrity", translation: "Integrität" },
            { word: "Respect", translation: "Respekt" },
            { word: "Kindness", translation: "Freundlichkeit" },
        ],
    },
    {
        name: "Travel Vocabulary",
        progress: 0,
        words: [
            { word: "Ticket", translation: "Fahrkarte" },
            { word: "Luggage", translation: "Gepäck" },
            { word: "Airport", translation: "Flughafen" },
            { word: "Train", translation: "Zug" },
        ],
    },
    {
        name: "Business Terms",
        progress: 100,
        words: [
            { word: "Negotiation", translation: "Verhandlung" },
            { word: "Invoice", translation: "Rechnung" },
            { word: "Profit", translation: "Gewinn" },
            { word: "Strategy", translation: "Strategie" },
            { word: "Contract", translation: "Vertrag" },
            { word: "Client", translation: "Kunde" },
            { word: "Presentation", translation: "Präsentation" },
            { word: "Budget", translation: "Haushalt" },
            { word: "Deadline", translation: "Frist" },
        ],
    },
    {
        name: "Daily Expressions",
        progress: 25,
        words: [
            { word: "Hello", translation: "Hallo" },
            { word: "Thank you", translation: "Danke" },
            { word: "Sorry", translation: "Entschuldigung" },
        ],
    },
    {
        name: "Food & Drink",
        progress: 75,
        words: [
            { word: "Bread", translation: "Brot" },
            { word: "Water", translation: "Wasser" },
            { word: "Apple", translation: "Apfel" },
            { word: "Cheese", translation: "Käse" },
            { word: "Coffee", translation: "Kaffee" },
            { word: "Juice", translation: "Saft" },
            { word: "Salt", translation: "Salz" },
            { word: "Butter", translation: "Butter" },
            { word: "Egg", translation: "Ei" },
            { word: "Fish", translation: "Fisch" },
        ],
    },
];

export const useVocabularyStore = create<VocabularyState>((set) => ({
    vocabulary: defaultVocabulary,
    vocabularies: defaultVocabularies,
    setVocabulary: (vocabulary) => set({ vocabulary }),
    setVocabularies: (vocabularies) => set({ vocabularies }),
    clearVocabulary: () => set({ vocabulary: null }),
    clearVocabularies: () => set({ vocabularies: [] }),
}));
