import {
    LayoutDashboard,
    Package,
    TreePine,
    BookText,
    TrendingUp,
    BookOpen,
    Users,
    Notebook,
    Workflow,
    Group,
    Text,
    FilePlus,
    Settings,
    Info,
    Compass,
    LandPlot,
    Activity,
    Layers,
    BookOpenText,
    Link2,
    LayoutGrid,
    Radio,
    Video,
    PencilLine,
    Mic,
    Stethoscope,
    Library,
    MessageSquareText,
    UploadCloud,
    DoorOpen,
    BookMarked,
    UserCog,
    Users2,
    BarChart4,
    Flag,
    TerminalSquare,
    FolderSearch,
    Settings2,
    FileText,
    ListOrdered,
    Map,
    AudioWaveform,
    Brain
} from "lucide-react";

export const iconMap = {
    LayoutDashboard: <LayoutDashboard size={18} />,
    Package: <Package size={18} />,
    TreePine: <TreePine size={18} />,
    BookText: <BookText size={18} />,
    TrendingUp: <TrendingUp size={18} />,
    BookOpen: <BookOpen size={18} />,
    Users: <Users size={18} />,
    Notebook: <Notebook size={18} />,
    Workflow: <Workflow size={18} />,
    Group: <Group size={18} />,
    Text: <Text size={18} />,
    FilePlus: <FilePlus size={18} />,
    Settings: <Settings size={18} />,
    Info: <Info size={18} />,
    Compass: <Compass size={18} />,
    LandPlot: <LandPlot size={18} />,
    Activity: <Activity size={18} />,
    Layers: <Layers size={18} />,
    BookOpenText: <BookOpenText size={18} />,
    Link2: <Link2 size={18} />,
    LayoutGrid: <LayoutGrid size={18} />,
    Radio: <Radio size={18} />,
    Video: <Video size={18} />,
    PencilLine: <PencilLine size={18} />,
    Mic: <Mic size={18} />,
    Stethoscope: <Stethoscope size={18} />,
    Library: <Library size={18} />,
    MessageSquareText: <MessageSquareText size={18} />,
    UploadCloud: <UploadCloud size={18} />,
    DoorOpen: <DoorOpen size={18} />,
    BookMarked: <BookMarked size={18} />,
    FileText: <FileText size={18} />,
    UserCog: <UserCog size={18} />,
    Users2: <Users2 size={18} />,
    BarChart4: <BarChart4 size={18} />,
    Flag: <Flag size={18} />,
    TerminalSquare: <TerminalSquare size={18} />,
    FolderSearch: <FolderSearch size={18} />,
    Settings2: <Settings2 size={18} />,
    ListOrdered: <ListOrdered size={18} />,
    Map: <Map size={18} />,
    Waveform: <AudioWaveform size={18} />,
    Brain: <Brain size={18} />
} as const;

export type IconName = keyof typeof iconMap;