import {
    LayoutDashboard,
    Package,
    TreePine,
    BookText,
    TrendingUp,
    BookOpen,
    Users,
    Notebook,
    Workflow,
    Group,
    Text,
    FilePlus,
    Settings,
    Info,
    Compass,
    LandPlot,
    Activity,
    Layers,
    BookOpenText,
    Link2,
    LayoutGrid,
} from "lucide-react";

export const iconMap = {
    LayoutDashboard: <LayoutDashboard size={18} />,
    Package: <Package size={18} />,
    TreePine: <TreePine size={18} />,
    BookText: <BookText size={18} />,
    TrendingUp: <TrendingUp size={18} />,
    BookOpen: <BookOpen size={18} />,
    Users: <Users size={18} />,
    Notebook: <Notebook size={18} />,
    Workflow: <Workflow size={18} />,
    Group: <Group size={18} />,
    Text: <Text size={18} />,
    FilePlus: <FilePlus size={18} />,
    Settings: <Settings size={18} />,
    Info: <Info size={18} />,
    Compass: <Compass size={18} />,
    LandPlot: <LandPlot size={18} />,
    Activity: <Activity size={18} />,
    Layers: <Layers size={18} />,
    BookOpenText: <BookOpenText size={18} />,
    Link2: <Link2 size={18} />,
    LayoutGrid: <LayoutGrid size={18} />,
} as const;

export type IconName = keyof typeof iconMap;